spring.application.name=backend

# Connection with MongoDB (local)
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/optitour

# JWT Configuration
OptiTour.jwt.secret=OptiTour_SuperSecretKey_2026_AtLeast256BitsLong_ForHS256Algorithm
OptiTour.jwt.expiration=86400000 
# 86400000 = 24 Hours
